### DISCUSSION TITLE
Got 500 Error

### DISCUSSION THREAD

**Discussion by sahansanathana** [tiredofit/docker-invoiceninja#3] [Q&A]
Hi there, I use lots of compose files like book stack, Nginx, WordPress etc.
I'm trying to deploy invoiceninja using your docker-compose file but I'm getting a 500 error, I use traefik as my reverse proxy

this is my compose file
[6z2ccvb7i4cpzhqg276o4qrps_logs.txt](https://github.com/tiredofit/docker-invoiceninja/files/10086592/6z2ccvb7i4cpzhqg276o4qrps_logs.txt)

```
version: '3.3'

services:
  
  invoiceninja-app:
    image: tiredofit/invoiceninja
    deploy:
      mode: replicated
      placement:  # use for deploy all the containers on manager node instead of worker nodes
        constraints:
          - node.role == manager # this is used to deploy this container forcefully on my manager node
      replicas: 1 # number of nodes
    networks:
      - elb
    restart: always
    container_name: invoiceninja-app
    volumes:
      ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
      - pv:/www/html
      ### Or, if you just want to use Stock invoiceninja and hold onto persistent files like cache and session use this, one or the other.
      - pv:/data
      ### If you want to just keep the original source and add additional modules uncomment this line
      - pv:/www/logs
    environment:
      - CONTAINER_NAME=invoiceninja-app
      - TIMEZONE=Asia/Colombo
      
      - DB_HOST=REMOTE_DB_HOSTNAME
      - DB_NAME=DB_CRED
      - DB_USER=DB_CRED
      - DB_PASS=DB_CRED

      - SITE_URL=https://invoice.MYDOMAIN.LK

      - ADMIN_EMAIL=MY_EMAIL
      - ADMIN_PASS=MY_PASS

      - ENABLE_SSL_PROXY=TRUE
      - DISPLAY_ERRORS=FALSE
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.invoiceninja.entrypoints=web, websecure"
      - "traefik.http.routers.invoiceninja.rule=Host(`invoice.MY_DOMAIN.LK`)"
      - "traefik.http.routers.invoiceninja.tls=true"
      - "traefik.http.routers.invoiceninja.tls.certresolver=production"
      - "traefik.http.routers.invoiceninja.service=invoiceninja_service"
      - "traefik.http.services.invoiceninja_service.loadbalancer.server.port=80"

volumes:
    pv:
        external: false
     
networks:
  elb:
    external:
      name: elb
```
