### ISSUE TITLE
No English language option or Canada country option

### ISSUE THREAD

**Issue by UntouchedWagons** [tiredofit/docker-invoiceninja#4]
### Summary

Upon first login I am prompted to enter my company name, first name, last name, language end currency. For some reason English and Canadian dollar aren't in the list. The American Dollar isn't even in the list

### Steps to reproduce

1. Login

### What is the expected *correct* behavior?

Be able to choose the English language and Canadian dollar.

### Environment

- Image version / tag:  tiredofit/invoiceninja
- Host OS: Ubuntu Server 22.04

```
version: "3.5"

services:
  invoiceninja_mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: invoiceninja_mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=RelieveFutureEarly
      - TZ=America/Toronto
      - MYSQL_DATABASE=invoiceninja
      - MYSQL_USER=invoiceninja
      - MYSQL_PASSWORD=DespoticLudicrousWorkerUnrestrained
    volumes:
      - ./appdata/mariadb:/config
    restart: unless-stopped

  invoiceninja:
    image: tiredofit/invoiceninja
    container_name: invoiceninja
    links:
      - invoiceninja_mariadb
    environment:
      - CONTAINER_NAME=invoiceninja
      - TIMEZONE=America/Toronto
      - DB_HOST=invoiceninja_mariadb
      - DB_NAME=invoiceninja
      - DB_USER=invoiceninja
      - DB_PASS=DespoticLudicrousWorkerUnrestrained
      - SITE_URL=https://invoiceninja.REDACTED
      - ADMIN_EMAIL=REDACTED
      - ADMIN_PASS=VehicleInductionPensiveThrush1
      - ENABLE_SSL_PROXY=TRUE
      - DISPLAY_ERRORS=FALSE
    networks:
      - default
      - docker_default
    restart: unless-stopped

networks:
  default:
  docker_default:
    external: true
```

![firefox_h0Upbn755g](https://user-images.githubusercontent.com/160996/210022643-a5eb8e9e-694e-4669-aca7-c764bcb00d7d.png)
