### ISSUE TITLE
Incorrect environment variable mapping `REDIS_HOST` being used for `REDIS_PORT`

### ISSUE THREAD

**Issue by ToshY** [tiredofit/docker-invoiceninja#8]
### Summary

Application throws 500 error due to an incorrect `REDIS_PORT` environment variable mapping.

![image](https://github.com/tiredofit/docker-invoiceninja/assets/31921460/98ff23bf-4063-451c-a92a-d0c73b0de8af)

### Steps to reproduce

Use the [example](https://github.com/tiredofit/docker-invoiceninja/blob/main/examples/compose.yml) setup but with additional `redis` service in stack

`.env`
```dotenv
REDIS_HOST="redis"
REDIS_PORT="6379"
REDIS_PASS="password"
```

`docker-compose.yml`

```yml
services:
  redis:
    image: redis:7.0-alpine
    command: redis-server --requirepass ${REDIS_PASS}
    environment:
      REDISCLI_AUTH: ${REDIS_PASS}
    networks:
      - invoiceninja
```

### What is the expected *correct* behavior?

No error; correct environment variable mapping.

### Environment

- Image version / tag:  `1.0.77`
- Host OS: `Ubuntu 22.04.2 LTS`
    
### Possible fixes

Error in mapping is found here.

https://github.com/tiredofit/docker-invoiceninja/blob/c4d5a970b5f86d32e9539bf06edd59cae7f77fb4/install/etc/cont-init.d/30-invoiceninja#L178
